language: ruby
rvm:
    - 2.0.0
services:
    - memcached
    - redis
env:
    global:
        - RAILS_ENV=test
        - DATABASE_USER=postgres
        - DATABASE_HOST=localhost
        - DEVISE_SECRET_KEY=1234abc
before_script:
    - psql -c 'create database gamocosm_test;' -U postgres
    - bundle exec rake db:schema:load
script: bundle exec rake test:functionals test:units
