vanilla:
    versions:
        - { name: Vanilla (1.8.8), tag: 1.8.8 }
        - { name: Vanilla (1.7.10), tag: 1.7.10 }
        - { name: Vanilla (1.7.2), tag: 1.7.2 }
        - { name: Vanilla (1.6.4), tag: 1.6.4 }
        - { name: Vanilla (1.5.2), tag: 1.5.2 }
        - { name: Vanilla (1.4.7), tag: 1.4.7 }
        - { name: Vanilla (1.3.2), tag: 1.3.2 }
        - { name: Vanilla (1.2.5), tag: 1.2.5 }
    time: 1
    developers:
        - Mojang
    website: https://minecraft.net
    notes: []
cuberite:
    versions:
        - { name: Cuberite, tag: "null" }
    time: 1
    developers:
        - Cuberite team
    website: http://cuberite.org
    notes: []
truecraft:
    versions:
        - { name: TrueCraft (beta 1.7.3), tag: beta-1.7.3 }
    time: 1
    developers:
        - SirCmpwn et al
    website: http://truecraft.io
    notes: []
forge:
    versions:
        - { name: Forge (1.8), tag: 1.8-11.14.1.1412 }
        - { name: Forge (1.7.10), tag: 1.7.10-10.13.2.1230 }
    time: 1
    developers:
        - Minecraft Forge team
    website: http://minecraftforge.net
    notes: []
spigot:
    versions:
        - { name: Spigot (1.8), tag: 1.8 }
    time: 10
    developers:
        - Spigot team
    website: http://spigotmc.org
    notes:
        - 1GB+ recommended
        - This involves a long build process. It occasionally fails and you can try again or install it manually
craftbukkit:
    versions:
        - { name: CraftBukkit (1.8), tag: 1.8 }
        - { name: CraftBukkit (beta 1.7.3), tag: b1.7.3 }
    time: 10
    developers:
        - Spigot team
        - CraftBukkit team
    website: http://spigotmc.org
    notes:
        - 1GB+ recommended
        - This involves a long build process. It occasionally fails and you can try again or install it manually
        - For beta 1.7.3, autoshutdown doesn't work as it doesn't support the query protocol
agrarian_skies:
    versions:
        - { name: Agrarian Skies (1.6.4), tag: 1.6.4 }
    time: 1
    developers:
        - Jadedcat
    website: http://forum.feed-the-beast.com/threads/41906/
    notes:
        - 2GB+ recommended
        - This script is not updated frequently!
ftb_resurrection:
    versions:
        - { name: FTB Resurrection (1.7.10), tag: 1.7.10 }
    time: 2
    developers:
        - FTB team
    website: http://feed-the-beast.com
    notes:
        - 2GB+ recommended
        - This script is not updated frequently!
crash_landing:
    versions:
        - { name: Crash Landing (1.6.4), tag: 1.6.4 }
    time: 1
    developers:
        - Iskandar
        - others
    website: http://forum.feed-the-beast.com/threads/46277/
    notes:
        - 2GB+ recommended
        - This script is not updated frequently!
direwolf20:
    versions:
        - { name: Direwolf20 (1.7.10), tag: 1.7.10 }
    time: 2
    developers:
        - FTB team
    website: http://feed-the-beast.com
    notes:
        - 2GB+ recommended
        - This script is not updated frequently!
tppi:
    versions:
        - { name: Test Pack Please Ignore (1.6.4), tag: 1.6.4 }
    time: 2
    developers:
        - TPPI team
    website: http://www.reddit.com/r/TestPackPleaseIgnore/
    notes:
        - 2GB+ recommended
        - This script is not updated frequently!
